[tool.poetry]
name = "homepy"
version = "0.1.0"
description = ""
authors = ["quirinal36 <with_i5@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
